import type { PlayerMock, PlayerTab } from "./types";

export const playerTabs: PlayerTab[] = ["For You", "Artists", "Following"];

export const playerMocks: PlayerMock[] = [
  {
    tab: "For You",
    handle: "@futuristic",
    caption: "It Is Not The Healthy Who Need A Doctor, But The Sick",
    tags: "#Newmusic #Bts #Morpheusai ... More",
    audio: "RIGHT BACK · Don Ready, Futuristic, C",
    lyric: "I ALMOST LEFT\nTHE CHURCH...",
    likes: "999K",
    comments: "999K",
    shares: "999K",
    saves: "999K",
    colors: ["#12c6ed", "#34bde9", "#1d5c83", "#080808"],
    avatarColors: ["#f59e0b", "#111827"],
    figureColor: "#111827",
    prop: "mic",
  },
  {
    tab: "For You",
    handle: "@ravn.wav",
    caption: "Midnight loop for the late rooms",
    tags: "#lofibeats #studio #morpheusai ... More",
    audio: "SLOW DRIFT · RAVN, Yuna Saitō",
    lyric: "MIDNIGHT\nROOM OPEN",
    likes: "742K",
    comments: "84K",
    shares: "51K",
    saves: "122K",
    colors: ["#101827", "#6d28d9", "#0f766e", "#050505"],
    avatarColors: ["#38bdf8", "#111827"],
    figureColor: "#241334",
    prop: "disc",
  },
  {
    tab: "Artists",
    handle: "@yunasaito",
    caption: "Ambient take from the live room",
    tags: "#ambient #wavroom #newdrop ... More",
    audio: "VOL. II · Yuna Saitō",
    lyric: "THE ROOM\nWENT QUIET",
    likes: "518K",
    comments: "42K",
    shares: "29K",
    saves: "91K",
    colors: ["#f8fafc", "#a7f3d0", "#0f766e", "#020617"],
    avatarColors: ["#a7f3d0", "#0f172a"],
    figureColor: "#164e63",
    prop: "stage",
  },
  {
    tab: "Artists",
    handle: "@kaito",
    caption: "Studio session before the drop",
    tags: "#stems #session #producer ... More",
    audio: "LULL · KAITO",
    lyric: "MAKING\nLULL",
    likes: "263K",
    comments: "19K",
    shares: "14K",
    saves: "47K",
    colors: ["#ff7b3d", "#7c2d12", "#1f2937", "#080808"],
    avatarColors: ["#fb923c", "#111827"],
    figureColor: "#1f2937",
    prop: "mic",
  },
  {
    tab: "Following",
    handle: "@ciel.vox",
    caption: "Demo pass for your next track",
    tags: "#topline #vocal #demo ... More",
    audio: "CONCRETE JUNGLE · Ciel",
    lyric: "SEND THE\nDEMO",
    likes: "126K",
    comments: "8K",
    shares: "6K",
    saves: "23K",
    colors: ["#fda4af", "#be123c", "#312e81", "#09090b"],
    avatarColors: ["#fda4af", "#111827"],
    figureColor: "#312e81",
    prop: "stage",
  },
  {
    tab: "Following",
    handle: "@studiohira",
    caption: "Cover system built from your brand bible",
    tags: "#coverart #brandbible #visuals ... More",
    audio: "STATIC COVER · Studio Hira",
    lyric: "ART IN\nSECONDS",
    likes: "88K",
    comments: "5K",
    shares: "3K",
    saves: "18K",
    colors: ["#f5f5f4", "#94a3b8", "#334155", "#020617"],
    avatarColors: ["#e5e7eb", "#111827"],
    figureColor: "#334155",
    prop: "disc",
  },
];

export const GESTURE_CAPTURE_THRESHOLD = 6;
export const SWIPE_COMMIT_THRESHOLD = 24;
export const SWIPE_VELOCITY_THRESHOLD = 0.22;
